### ISSUE TITLE
Обеспечить единую точку доступа.

### ISSUE THREAD

**Issue by alexandr-poloz** [simplexwebsystems/simplex#2]
Реализация через .htaccess это замечательно но не кроссплатформенно. Нужна возможность блокировать прямой доступ к файлам если сервер не апач (тоесть не поддержевает .htaccess).
На програмном уровне это означает что мы в индекс создаем ститическую переменную ACCESS и в каждом файле скрипта добавляем:

if(ACCESS !== true) die("ACCESS ERROR!");
или
!ACCESS ? die("ACCESS ERROR!") : NULL;

**Comment by alexandr-poloz** [comment]
Таки будут иные предложения ?

**Comment by mantisa** [comment]
пара замечаний:
не статическую переменную, а константу. пускай себе будет ACCESS (походу ты про константу и говоришь).
по-моему наиболее лаконичный код проверки:
ACCESS || die("DIRECT ACCESS DENIED!");

**Comment by alexandr-poloz** [comment]
Океюшки. Одобряю :).

**Comment by mantisa** [comment]
гыгы

2013/6/14 Alexanr Poloz notifications@github.com

**Comment by alexandr-poloz** [comment]
Если создаешь папку, положи туда файл index.html
c текстом DIRECT ACCESS DENIED!
