### ISSUE TITLE
Механизм автоподключения

### ISSUE THREAD

**Issue by alexandr-poloz** [simplexwebsystems/simplex#3]
## Класс Loader или Linker

Единственный экземпляр
## Определяет положение файла с объявлением класса по названию пространства имен к которому принадлежит искомый класс.

Пример:
Пусть есть пространство имен A, файлы с объявлением классов которого мы размещаем в директории path/to/a .
Тогда чтобы все классы из этого пространства искалиь в папке path/to/a следует выполнить след. код:

Loader::i()->fixNameSpace("A","path/to/a");

Далее мы пытаемся создать ранее не объявленный класс A\subNMSPC\ClassName : 
$a = new A\subNMSPC\ClassName();
subNMSPC - подпостранство  пространства имен A

В результате будет выполнена попытка подключения файла:
path/to/a/subNMSPC/ClassName.php

---

Объект автозагрузчика должен уметь подключать стороние каллбэки для определения положения файла с объявлением в случае если подключаемая стороння библиотека исплользует свой механизм подключения.

**Comment by mantisa** [comment]
🗡️ 👍 :)
:D
